#!/bin/sh
# commitlint SUBJECT - lint your commits by conventionalcommits spec
#
# https://www.conventionalcommits.org/en/v1.0.0/
#
# EXAMPLE:
# 	git show --no-patch --pretty='format:%s' | commitlint
# 	commitlint "feat: foo"

set -eu

error() {
	printf 'ERROR: "%s" - %s\n' "$(head -n1 "$SRC")" "$@" >&2
	exit 1
}

lint() {
	pattern="$1"
	head -n1 "$SRC" | grep -q -E "$pattern"
}

if [ -p /dev/stdin ]; then
	# save piped data to file, as we need to read it multiple times
	f="$(mktemp)" && trap 'rm $f' 0
	cat /dev/stdin >"$f"
	set -- "$f"
elif [ "$#" -gt 0 ]; then
	:
else
	error "Invalid input"
fi

for f; do
	SRC="$f"

	# custom rules
	lint "^initial commit$" && continue
	lint '^Revert ".+"' && continue

	# https://github.com/conventional-changelog/commitlint/tree/b12ec06/%40commitlint/config-conventional

	scope="(|\([[:alnum:]\/_-]+\))"

	## type
	lint "^[a-zA-Z]+.*:" || error "missing TYPE. use '{TYPE}: {SUBJECT}'"
	lint "^[a-z]+.*:" || error "TYPE needs to start with lowercase word"
	lint "^(build|chore|ci|docs?|feat|fix|perf|refactor|revert|style|tests?)[^[:alnum:]]+" || error "invalid TYPE"

	# breaking indicator
	lint "^[a-z]+(|\(.*\))(|!):" || error "Breaking Indicator malformed"

	## scope
	lint "^[a-z]+${scope}(|!):" || error "SCOPE malformed"

	## subject
	lint "^[a-z]+.*: [a-z]" || error "SUBJECT needs to start with lowercase word"
	lint "^[a-z]+.*: [a-z].{2,}" || error "SUBJECT is expected to be at least 3 chars"
	lint "[^\.]$" || error "SUBJECT should not end with full-stop"
done
